[workspace]
members = [
    "crates/shared",
    "crates/cli",
    "crates/api"
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
name = "anzar"
description = "Anzar is a lightweight authentication and authorization framework that runs as a separate microservice"
readme = "README.md"
license = "GPL-3.0"
version = "0.8.6"
authors = ["Hakou Guelfen <hakoudev@gmail.com>"]
homepage = "https://anzar_software.gitlab.io/docs"
repository = "https://gitlab.com/anzar_software/api"
categories = ["authentication", "web-programming", "network-programming"]
keywords = [
  "Software Development",
  "Authentication",
  "Authorization",
  "MicroService"
]

[workspace.dependencies]
# Define shared dependencies here to manage versions in one place
tokio = "1.48.0"
chrono = { version = "0.4.37", features = ["serde"] }
actix-session = { version = "0.11.0", features = ["cookie-session", "redis-session"] }

serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
serde_json = "1.0.115"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }

# Database
sqlx = { version = "0.8.6", features = ["sqlite", "postgres", "runtime-tokio", "tls-rustls-ring-webpki", "uuid", "chrono", "json"] }
mongodb = { version = "3.6.0" }
memcache = { version = "0.19", default-features = false }
redis = { version = "1.2", features = ["tokio-comp", "connection-manager"] }

# Tracing
tracing = { version = "0.1.40", features = ["log"] }
tracing-bunyan-formatter = "0.3.9"
tracing-subscriber = { version = "0.3.18", features = ["registry", "env-filter"] }
tracing-actix-web = "0.7.14"
tracing-opentelemetry = "0.32"
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31", features = ["tonic"] }
opentelemetry_sdk = "0.31"

# Utoipa
utoipa = { version = "5.4.0", features = ["chrono", "actix_extras", "yaml"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web", "vendored"] }

# Cryptography
base64 = "0.22.1"
openssl = { version = "0.10.80", features = ["vendored"] }
rand = "0.9.1"

validator = { version = "0.20.0", features = ["derive"] }
secrecy = { version = "0.10.3", features = ["serde"] }
config = "0.15.19"
dotenvy = "0.15.7"

thiserror = "2.0.18"

[profile.release]
opt-level = 'z'          # Optimize for size
lto = true               # Link-time optimization
codegen-units = 1        # Better optimization, slower compile
panic = 'abort'          # Remove panic unwinding
strip = true             # Strip symbols in cargo

# Optional: Further size reduction
[profile.release.package."*"]
opt-level = 'z'
strip = true
