[package]
name = "shared"
version.workspace = true
edition.workspace = true


[lib]
name = "shared"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }

actix-session = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }

# Database
sqlx = { workspace = true }
mongodb = { workspace = true }
memcache = { workspace = true }
redis = { workspace = true }

# Tracing
tracing = { workspace = true }
tracing-bunyan-formatter = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-actix-web = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }

utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

# Cryptography
base64 = { workspace = true }
openssl = { workspace = true }
rand = { workspace = true }

validator = { workspace = true }
secrecy = { workspace = true }
config = { workspace = true }
thiserror = { workspace = true }

#------------------------------------------
async-trait = "0.1.82"

# Cryptography
sha2 = "0.10.9"
argon2 = "0.5.3"
bcrypt = "0.19.0"
hmac = "0.12.1"
aes-gcm = "0.10.3"
hex = "0.4.3"
uuid = "1.18.1"

dashmap = "6.1.0"
futures = "0.3.32"

